ARG IMAGE
FROM $IMAGE
MAINTAINER Romain Beauxis <toots@rastageeks.org>

ARG OPAM_PKG

ARG PKG_CONFIG_PATH

USER root

USER opam

RUN opam list --short --recursive --external --vars os-distribution=mxe,os-family=mingw --required-by=$OPAM_PKG > /home/opam/mxe-deps

USER root

RUN cd /usr/src/mxe/ && git fetch && \
    git config --global user.email "test@test.com" && \
    git config --global user.name "Test CI" && \
    git cherry-pick 254fe06cde7fa787a9ce1a264f04bbc9443c7f57

RUN cd /usr/src/mxe/ && cat /home/opam/mxe-deps | xargs make

USER opam

RUN eval $(opam env) && opam reinstall --verbose -y $OPAM_PKG
